/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContainersRouteImport } from './routes/containers'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as NetworksRouteImport } from './routes/networks'
import { Route as SystemRouteImport } from './routes/system'
import { Route as VolumesRouteImport } from './routes/volumes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersRoute = ContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworksRoute = NetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumesRoute = VolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/containers': typeof ContainersRoute
  '/images': typeof ImagesRoute
  '/networks': typeof NetworksRoute
  '/system': typeof SystemRoute
  '/volumes': typeof VolumesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/containers': typeof ContainersRoute
  '/images': typeof ImagesRoute
  '/networks': typeof NetworksRoute
  '/system': typeof SystemRoute
  '/volumes': typeof VolumesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/containers': typeof ContainersRoute
  '/images': typeof ImagesRoute
  '/networks': typeof NetworksRoute
  '/system': typeof SystemRoute
  '/volumes': typeof VolumesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/containers' | '/images' | '/networks' | '/system' | '/volumes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/containers' | '/images' | '/networks' | '/system' | '/volumes'
  id:
    | '__root__'
    | '/'
    | '/containers'
    | '/images'
    | '/networks'
    | '/system'
    | '/volumes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContainersRoute: typeof ContainersRoute
  ImagesRoute: typeof ImagesRoute
  NetworksRoute: typeof NetworksRoute
  SystemRoute: typeof SystemRoute
  VolumesRoute: typeof VolumesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers': {
      id: '/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof ContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networks': {
      id: '/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof NetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volumes': {
      id: '/volumes'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof VolumesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContainersRoute: ContainersRoute,
  ImagesRoute: ImagesRoute,
  NetworksRoute: NetworksRoute,
  SystemRoute: SystemRoute,
  VolumesRoute: VolumesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
